version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: talkflow-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./server
    container_name: talkflow-backend
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/talkflow
    depends_on:
      - mongodb

  frontend:
    build: ./client
    container_name: talkflow-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend

volumes:
  mongo-data:
